# Generated by Django 3.2.6 on 2021-08-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('1', 'CARD'), ('2', 'CASH')], max_length=10)),
                ('status', models.CharField(choices=[('1', 'PROCESSING'), ('2', 'RECEIVED'), ('3', 'DELIVERED')], max_length=10)),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productdetails')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
