# Generated by Django 3.2.6 on 2021-08-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_orderproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproducts',
            options={'verbose_name': 'Order Product', 'verbose_name_plural': 'Orders Products'},
        ),
        migrations.RenameField(
            model_name='productdetails',
            old_name='cantity',
            new_name='quantity',
        ),
    ]
