# Generated by Django 3.2.6 on 2021-08-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210831_1210'),
        ('shop', '0012_auto_20210831_1243'),
    ]

    operations = [
    ]
