# Generated by Django 3.2.6 on 2021-08-31 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_merge_0012_auto_20210831_1210_0012_auto_20210831_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productillustration',
            options={'verbose_name': 'Product Illustration', 'verbose_name_plural': 'Products Illustrations'},
        ),
        migrations.AddField(
            model_name='illustration',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='productillustration',
            unique_together={('product', 'illustration')},
        ),
        migrations.CreateModel(
            name='IllustrationProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'T-Shirts'), ('2', 'Hoodies'), ('3', 'Mugs'), ('4', 'Totebags')], max_length=10)),
                ('illustration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.illustration')),
            ],
        ),
    ]
