# Generated by Django 3.2.6 on 2021-09-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_illustration_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='illustration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.illustration'),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='illustration_from_user',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
