# Generated by Django 3.2.6 on 2021-09-01 18:02

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20210901_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=shop.models.in_three_days),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'PROCESSING'), ('2', 'RECEIVED'), ('3', 'DELIVERED')], default=1, max_length=10),
        ),
    ]
